language: python
python:
  - "2.7"
env:
  - DJANGO=Django==1.5.4 TEST_DB=sqlite
  - DJANGO=Django==1.5.4 TEST_DB=mysql

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -q $DJANGO --use-mirrors
before_script:
  - python -c "import django; print(django.get_version())"
  - sudo apt-get install libjpeg-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
  - pip install -I PIL
  - mysql -e 'create database offer_listings;'
  - psql -c 'create database offer_listings;' -U postgres
script:
    - fab work.test
